#' Batch concurrent benchmark results
#'
#' Benchmark data comparing different batch sizes and concurrent request
#' configurations for Hugging Face API calls.
#'
#' @format A data frame with 20 rows and 7 variables:
#' \describe{
#'   \item{batch_size}{Integer; size of each batch processed}
#'   \item{concurrent_requests}{Integer; number of concurrent requests}
#'   \item{chunk_index}{Integer; index of the processed chunk}
#'   \item{elapsed_time}{Numeric; time taken in seconds}
#'   \item{success}{Logical; whether the operation succeeded}
#'   \item{rows_processed}{Integer; number of rows successfully processed}
#'   \item{throughput}{Numeric; requests processed per second}
#' }
#' @source Internal benchmarking of EndpointR functions
"batch_concurrent_benchmark"

#' Example embedding results from Hugging Face API
#'
#' A sample dataset containing text embeddings generated using Hugging Face's
#' embedding API. This dataset demonstrates the structure of results returned
#' by the `hf_embed_batch()` and `hf_embed_df()` functions.
#'
#' @format A data frame with 3 rows and 773 variables:
#' \describe{
#'   \item{id}{Integer; unique identifier for each text}
#'   \item{text}{Character; the original text that was embedded}
#'   \item{category}{Character; category classification of the text}
#'   \item{.error}{Logical; whether the embedding process failed}
#'   \item{.error_msg}{Character; error message if embedding failed (NA if successful)}
#' \item{V1}{Numeric; embedding vector dimensions}
#' \item{V2}{Numeric; embedding vector dimensions}
#' \item{V3}{Numeric; embedding vector dimensions}
#' \item{V4}{Numeric; embedding vector dimensions}
#' \item{V5}{Numeric; embedding vector dimensions}
#' \item{V6}{Numeric; embedding vector dimensions}
#' \item{V7}{Numeric; embedding vector dimensions}
#' \item{V8}{Numeric; embedding vector dimensions}
#' \item{V9}{Numeric; embedding vector dimensions}
#' \item{V10}{Numeric; embedding vector dimensions}
#' \item{V11}{Numeric; embedding vector dimensions}
#' \item{V12}{Numeric; embedding vector dimensions}
#' \item{V13}{Numeric; embedding vector dimensions}
#' \item{V14}{Numeric; embedding vector dimensions}
#' \item{V15}{Numeric; embedding vector dimensions}
#' \item{V16}{Numeric; embedding vector dimensions}
#' \item{V17}{Numeric; embedding vector dimensions}
#' \item{V18}{Numeric; embedding vector dimensions}
#' \item{V19}{Numeric; embedding vector dimensions}
#' \item{V20}{Numeric; embedding vector dimensions}
#' \item{V21}{Numeric; embedding vector dimensions}
#' \item{V22}{Numeric; embedding vector dimensions}
#' \item{V23}{Numeric; embedding vector dimensions}
#' \item{V24}{Numeric; embedding vector dimensions}
#' \item{V25}{Numeric; embedding vector dimensions}
#' \item{V26}{Numeric; embedding vector dimensions}
#' \item{V27}{Numeric; embedding vector dimensions}
#' \item{V28}{Numeric; embedding vector dimensions}
#' \item{V29}{Numeric; embedding vector dimensions}
#' \item{V30}{Numeric; embedding vector dimensions}
#' \item{V31}{Numeric; embedding vector dimensions}
#' \item{V32}{Numeric; embedding vector dimensions}
#' \item{V33}{Numeric; embedding vector dimensions}
#' \item{V34}{Numeric; embedding vector dimensions}
#' \item{V35}{Numeric; embedding vector dimensions}
#' \item{V36}{Numeric; embedding vector dimensions}
#' \item{V37}{Numeric; embedding vector dimensions}
#' \item{V38}{Numeric; embedding vector dimensions}
#' \item{V39}{Numeric; embedding vector dimensions}
#' \item{V40}{Numeric; embedding vector dimensions}
#' \item{V41}{Numeric; embedding vector dimensions}
#' \item{V42}{Numeric; embedding vector dimensions}
#' \item{V43}{Numeric; embedding vector dimensions}
#' \item{V44}{Numeric; embedding vector dimensions}
#' \item{V45}{Numeric; embedding vector dimensions}
#' \item{V46}{Numeric; embedding vector dimensions}
#' \item{V47}{Numeric; embedding vector dimensions}
#' \item{V48}{Numeric; embedding vector dimensions}
#' \item{V49}{Numeric; embedding vector dimensions}
#' \item{V50}{Numeric; embedding vector dimensions}
#' \item{V51}{Numeric; embedding vector dimensions}
#' \item{V52}{Numeric; embedding vector dimensions}
#' \item{V53}{Numeric; embedding vector dimensions}
#' \item{V54}{Numeric; embedding vector dimensions}
#' \item{V55}{Numeric; embedding vector dimensions}
#' \item{V56}{Numeric; embedding vector dimensions}
#' \item{V57}{Numeric; embedding vector dimensions}
#' \item{V58}{Numeric; embedding vector dimensions}
#' \item{V59}{Numeric; embedding vector dimensions}
#' \item{V60}{Numeric; embedding vector dimensions}
#' \item{V61}{Numeric; embedding vector dimensions}
#' \item{V62}{Numeric; embedding vector dimensions}
#' \item{V63}{Numeric; embedding vector dimensions}
#' \item{V64}{Numeric; embedding vector dimensions}
#' \item{V65}{Numeric; embedding vector dimensions}
#' \item{V66}{Numeric; embedding vector dimensions}
#' \item{V67}{Numeric; embedding vector dimensions}
#' \item{V68}{Numeric; embedding vector dimensions}
#' \item{V69}{Numeric; embedding vector dimensions}
#' \item{V70}{Numeric; embedding vector dimensions}
#' \item{V71}{Numeric; embedding vector dimensions}
#' \item{V72}{Numeric; embedding vector dimensions}
#' \item{V73}{Numeric; embedding vector dimensions}
#' \item{V74}{Numeric; embedding vector dimensions}
#' \item{V75}{Numeric; embedding vector dimensions}
#' \item{V76}{Numeric; embedding vector dimensions}
#' \item{V77}{Numeric; embedding vector dimensions}
#' \item{V78}{Numeric; embedding vector dimensions}
#' \item{V79}{Numeric; embedding vector dimensions}
#' \item{V80}{Numeric; embedding vector dimensions}
#' \item{V81}{Numeric; embedding vector dimensions}
#' \item{V82}{Numeric; embedding vector dimensions}
#' \item{V83}{Numeric; embedding vector dimensions}
#' \item{V84}{Numeric; embedding vector dimensions}
#' \item{V85}{Numeric; embedding vector dimensions}
#' \item{V86}{Numeric; embedding vector dimensions}
#' \item{V87}{Numeric; embedding vector dimensions}
#' \item{V88}{Numeric; embedding vector dimensions}
#' \item{V89}{Numeric; embedding vector dimensions}
#' \item{V90}{Numeric; embedding vector dimensions}
#' \item{V91}{Numeric; embedding vector dimensions}
#' \item{V92}{Numeric; embedding vector dimensions}
#' \item{V93}{Numeric; embedding vector dimensions}
#' \item{V94}{Numeric; embedding vector dimensions}
#' \item{V95}{Numeric; embedding vector dimensions}
#' \item{V96}{Numeric; embedding vector dimensions}
#' \item{V97}{Numeric; embedding vector dimensions}
#' \item{V98}{Numeric; embedding vector dimensions}
#' \item{V99}{Numeric; embedding vector dimensions}
#' \item{V100}{Numeric; embedding vector dimensions}
#' \item{V101}{Numeric; embedding vector dimensions}
#' \item{V102}{Numeric; embedding vector dimensions}
#' \item{V103}{Numeric; embedding vector dimensions}
#' \item{V104}{Numeric; embedding vector dimensions}
#' \item{V105}{Numeric; embedding vector dimensions}
#' \item{V106}{Numeric; embedding vector dimensions}
#' \item{V107}{Numeric; embedding vector dimensions}
#' \item{V108}{Numeric; embedding vector dimensions}
#' \item{V109}{Numeric; embedding vector dimensions}
#' \item{V110}{Numeric; embedding vector dimensions}
#' \item{V111}{Numeric; embedding vector dimensions}
#' \item{V112}{Numeric; embedding vector dimensions}
#' \item{V113}{Numeric; embedding vector dimensions}
#' \item{V114}{Numeric; embedding vector dimensions}
#' \item{V115}{Numeric; embedding vector dimensions}
#' \item{V116}{Numeric; embedding vector dimensions}
#' \item{V117}{Numeric; embedding vector dimensions}
#' \item{V118}{Numeric; embedding vector dimensions}
#' \item{V119}{Numeric; embedding vector dimensions}
#' \item{V120}{Numeric; embedding vector dimensions}
#' \item{V121}{Numeric; embedding vector dimensions}
#' \item{V122}{Numeric; embedding vector dimensions}
#' \item{V123}{Numeric; embedding vector dimensions}
#' \item{V124}{Numeric; embedding vector dimensions}
#' \item{V125}{Numeric; embedding vector dimensions}
#' \item{V126}{Numeric; embedding vector dimensions}
#' \item{V127}{Numeric; embedding vector dimensions}
#' \item{V128}{Numeric; embedding vector dimensions}
#' \item{V129}{Numeric; embedding vector dimensions}
#' \item{V130}{Numeric; embedding vector dimensions}
#' \item{V131}{Numeric; embedding vector dimensions}
#' \item{V132}{Numeric; embedding vector dimensions}
#' \item{V133}{Numeric; embedding vector dimensions}
#' \item{V134}{Numeric; embedding vector dimensions}
#' \item{V135}{Numeric; embedding vector dimensions}
#' \item{V136}{Numeric; embedding vector dimensions}
#' \item{V137}{Numeric; embedding vector dimensions}
#' \item{V138}{Numeric; embedding vector dimensions}
#' \item{V139}{Numeric; embedding vector dimensions}
#' \item{V140}{Numeric; embedding vector dimensions}
#' \item{V141}{Numeric; embedding vector dimensions}
#' \item{V142}{Numeric; embedding vector dimensions}
#' \item{V143}{Numeric; embedding vector dimensions}
#' \item{V144}{Numeric; embedding vector dimensions}
#' \item{V145}{Numeric; embedding vector dimensions}
#' \item{V146}{Numeric; embedding vector dimensions}
#' \item{V147}{Numeric; embedding vector dimensions}
#' \item{V148}{Numeric; embedding vector dimensions}
#' \item{V149}{Numeric; embedding vector dimensions}
#' \item{V150}{Numeric; embedding vector dimensions}
#' \item{V151}{Numeric; embedding vector dimensions}
#' \item{V152}{Numeric; embedding vector dimensions}
#' \item{V153}{Numeric; embedding vector dimensions}
#' \item{V154}{Numeric; embedding vector dimensions}
#' \item{V155}{Numeric; embedding vector dimensions}
#' \item{V156}{Numeric; embedding vector dimensions}
#' \item{V157}{Numeric; embedding vector dimensions}
#' \item{V158}{Numeric; embedding vector dimensions}
#' \item{V159}{Numeric; embedding vector dimensions}
#' \item{V160}{Numeric; embedding vector dimensions}
#' \item{V161}{Numeric; embedding vector dimensions}
#' \item{V162}{Numeric; embedding vector dimensions}
#' \item{V163}{Numeric; embedding vector dimensions}
#' \item{V164}{Numeric; embedding vector dimensions}
#' \item{V165}{Numeric; embedding vector dimensions}
#' \item{V166}{Numeric; embedding vector dimensions}
#' \item{V167}{Numeric; embedding vector dimensions}
#' \item{V168}{Numeric; embedding vector dimensions}
#' \item{V169}{Numeric; embedding vector dimensions}
#' \item{V170}{Numeric; embedding vector dimensions}
#' \item{V171}{Numeric; embedding vector dimensions}
#' \item{V172}{Numeric; embedding vector dimensions}
#' \item{V173}{Numeric; embedding vector dimensions}
#' \item{V174}{Numeric; embedding vector dimensions}
#' \item{V175}{Numeric; embedding vector dimensions}
#' \item{V176}{Numeric; embedding vector dimensions}
#' \item{V177}{Numeric; embedding vector dimensions}
#' \item{V178}{Numeric; embedding vector dimensions}
#' \item{V179}{Numeric; embedding vector dimensions}
#' \item{V180}{Numeric; embedding vector dimensions}
#' \item{V181}{Numeric; embedding vector dimensions}
#' \item{V182}{Numeric; embedding vector dimensions}
#' \item{V183}{Numeric; embedding vector dimensions}
#' \item{V184}{Numeric; embedding vector dimensions}
#' \item{V185}{Numeric; embedding vector dimensions}
#' \item{V186}{Numeric; embedding vector dimensions}
#' \item{V187}{Numeric; embedding vector dimensions}
#' \item{V188}{Numeric; embedding vector dimensions}
#' \item{V189}{Numeric; embedding vector dimensions}
#' \item{V190}{Numeric; embedding vector dimensions}
#' \item{V191}{Numeric; embedding vector dimensions}
#' \item{V192}{Numeric; embedding vector dimensions}
#' \item{V193}{Numeric; embedding vector dimensions}
#' \item{V194}{Numeric; embedding vector dimensions}
#' \item{V195}{Numeric; embedding vector dimensions}
#' \item{V196}{Numeric; embedding vector dimensions}
#' \item{V197}{Numeric; embedding vector dimensions}
#' \item{V198}{Numeric; embedding vector dimensions}
#' \item{V199}{Numeric; embedding vector dimensions}
#' \item{V200}{Numeric; embedding vector dimensions}
#' \item{V201}{Numeric; embedding vector dimensions}
#' \item{V202}{Numeric; embedding vector dimensions}
#' \item{V203}{Numeric; embedding vector dimensions}
#' \item{V204}{Numeric; embedding vector dimensions}
#' \item{V205}{Numeric; embedding vector dimensions}
#' \item{V206}{Numeric; embedding vector dimensions}
#' \item{V207}{Numeric; embedding vector dimensions}
#' \item{V208}{Numeric; embedding vector dimensions}
#' \item{V209}{Numeric; embedding vector dimensions}
#' \item{V210}{Numeric; embedding vector dimensions}
#' \item{V211}{Numeric; embedding vector dimensions}
#' \item{V212}{Numeric; embedding vector dimensions}
#' \item{V213}{Numeric; embedding vector dimensions}
#' \item{V214}{Numeric; embedding vector dimensions}
#' \item{V215}{Numeric; embedding vector dimensions}
#' \item{V216}{Numeric; embedding vector dimensions}
#' \item{V217}{Numeric; embedding vector dimensions}
#' \item{V218}{Numeric; embedding vector dimensions}
#' \item{V219}{Numeric; embedding vector dimensions}
#' \item{V220}{Numeric; embedding vector dimensions}
#' \item{V221}{Numeric; embedding vector dimensions}
#' \item{V222}{Numeric; embedding vector dimensions}
#' \item{V223}{Numeric; embedding vector dimensions}
#' \item{V224}{Numeric; embedding vector dimensions}
#' \item{V225}{Numeric; embedding vector dimensions}
#' \item{V226}{Numeric; embedding vector dimensions}
#' \item{V227}{Numeric; embedding vector dimensions}
#' \item{V228}{Numeric; embedding vector dimensions}
#' \item{V229}{Numeric; embedding vector dimensions}
#' \item{V230}{Numeric; embedding vector dimensions}
#' \item{V231}{Numeric; embedding vector dimensions}
#' \item{V232}{Numeric; embedding vector dimensions}
#' \item{V233}{Numeric; embedding vector dimensions}
#' \item{V234}{Numeric; embedding vector dimensions}
#' \item{V235}{Numeric; embedding vector dimensions}
#' \item{V236}{Numeric; embedding vector dimensions}
#' \item{V237}{Numeric; embedding vector dimensions}
#' \item{V238}{Numeric; embedding vector dimensions}
#' \item{V239}{Numeric; embedding vector dimensions}
#' \item{V240}{Numeric; embedding vector dimensions}
#' \item{V241}{Numeric; embedding vector dimensions}
#' \item{V242}{Numeric; embedding vector dimensions}
#' \item{V243}{Numeric; embedding vector dimensions}
#' \item{V244}{Numeric; embedding vector dimensions}
#' \item{V245}{Numeric; embedding vector dimensions}
#' \item{V246}{Numeric; embedding vector dimensions}
#' \item{V247}{Numeric; embedding vector dimensions}
#' \item{V248}{Numeric; embedding vector dimensions}
#' \item{V249}{Numeric; embedding vector dimensions}
#' \item{V250}{Numeric; embedding vector dimensions}
#' \item{V251}{Numeric; embedding vector dimensions}
#' \item{V252}{Numeric; embedding vector dimensions}
#' \item{V253}{Numeric; embedding vector dimensions}
#' \item{V254}{Numeric; embedding vector dimensions}
#' \item{V255}{Numeric; embedding vector dimensions}
#' \item{V256}{Numeric; embedding vector dimensions}
#' \item{V257}{Numeric; embedding vector dimensions}
#' \item{V258}{Numeric; embedding vector dimensions}
#' \item{V259}{Numeric; embedding vector dimensions}
#' \item{V260}{Numeric; embedding vector dimensions}
#' \item{V261}{Numeric; embedding vector dimensions}
#' \item{V262}{Numeric; embedding vector dimensions}
#' \item{V263}{Numeric; embedding vector dimensions}
#' \item{V264}{Numeric; embedding vector dimensions}
#' \item{V265}{Numeric; embedding vector dimensions}
#' \item{V266}{Numeric; embedding vector dimensions}
#' \item{V267}{Numeric; embedding vector dimensions}
#' \item{V268}{Numeric; embedding vector dimensions}
#' \item{V269}{Numeric; embedding vector dimensions}
#' \item{V270}{Numeric; embedding vector dimensions}
#' \item{V271}{Numeric; embedding vector dimensions}
#' \item{V272}{Numeric; embedding vector dimensions}
#' \item{V273}{Numeric; embedding vector dimensions}
#' \item{V274}{Numeric; embedding vector dimensions}
#' \item{V275}{Numeric; embedding vector dimensions}
#' \item{V276}{Numeric; embedding vector dimensions}
#' \item{V277}{Numeric; embedding vector dimensions}
#' \item{V278}{Numeric; embedding vector dimensions}
#' \item{V279}{Numeric; embedding vector dimensions}
#' \item{V280}{Numeric; embedding vector dimensions}
#' \item{V281}{Numeric; embedding vector dimensions}
#' \item{V282}{Numeric; embedding vector dimensions}
#' \item{V283}{Numeric; embedding vector dimensions}
#' \item{V284}{Numeric; embedding vector dimensions}
#' \item{V285}{Numeric; embedding vector dimensions}
#' \item{V286}{Numeric; embedding vector dimensions}
#' \item{V287}{Numeric; embedding vector dimensions}
#' \item{V288}{Numeric; embedding vector dimensions}
#' \item{V289}{Numeric; embedding vector dimensions}
#' \item{V290}{Numeric; embedding vector dimensions}
#' \item{V291}{Numeric; embedding vector dimensions}
#' \item{V292}{Numeric; embedding vector dimensions}
#' \item{V293}{Numeric; embedding vector dimensions}
#' \item{V294}{Numeric; embedding vector dimensions}
#' \item{V295}{Numeric; embedding vector dimensions}
#' \item{V296}{Numeric; embedding vector dimensions}
#' \item{V297}{Numeric; embedding vector dimensions}
#' \item{V298}{Numeric; embedding vector dimensions}
#' \item{V299}{Numeric; embedding vector dimensions}
#' \item{V300}{Numeric; embedding vector dimensions}
#' \item{V301}{Numeric; embedding vector dimensions}
#' \item{V302}{Numeric; embedding vector dimensions}
#' \item{V303}{Numeric; embedding vector dimensions}
#' \item{V304}{Numeric; embedding vector dimensions}
#' \item{V305}{Numeric; embedding vector dimensions}
#' \item{V306}{Numeric; embedding vector dimensions}
#' \item{V307}{Numeric; embedding vector dimensions}
#' \item{V308}{Numeric; embedding vector dimensions}
#' \item{V309}{Numeric; embedding vector dimensions}
#' \item{V310}{Numeric; embedding vector dimensions}
#' \item{V311}{Numeric; embedding vector dimensions}
#' \item{V312}{Numeric; embedding vector dimensions}
#' \item{V313}{Numeric; embedding vector dimensions}
#' \item{V314}{Numeric; embedding vector dimensions}
#' \item{V315}{Numeric; embedding vector dimensions}
#' \item{V316}{Numeric; embedding vector dimensions}
#' \item{V317}{Numeric; embedding vector dimensions}
#' \item{V318}{Numeric; embedding vector dimensions}
#' \item{V319}{Numeric; embedding vector dimensions}
#' \item{V320}{Numeric; embedding vector dimensions}
#' \item{V321}{Numeric; embedding vector dimensions}
#' \item{V322}{Numeric; embedding vector dimensions}
#' \item{V323}{Numeric; embedding vector dimensions}
#' \item{V324}{Numeric; embedding vector dimensions}
#' \item{V325}{Numeric; embedding vector dimensions}
#' \item{V326}{Numeric; embedding vector dimensions}
#' \item{V327}{Numeric; embedding vector dimensions}
#' \item{V328}{Numeric; embedding vector dimensions}
#' \item{V329}{Numeric; embedding vector dimensions}
#' \item{V330}{Numeric; embedding vector dimensions}
#' \item{V331}{Numeric; embedding vector dimensions}
#' \item{V332}{Numeric; embedding vector dimensions}
#' \item{V333}{Numeric; embedding vector dimensions}
#' \item{V334}{Numeric; embedding vector dimensions}
#' \item{V335}{Numeric; embedding vector dimensions}
#' \item{V336}{Numeric; embedding vector dimensions}
#' \item{V337}{Numeric; embedding vector dimensions}
#' \item{V338}{Numeric; embedding vector dimensions}
#' \item{V339}{Numeric; embedding vector dimensions}
#' \item{V340}{Numeric; embedding vector dimensions}
#' \item{V341}{Numeric; embedding vector dimensions}
#' \item{V342}{Numeric; embedding vector dimensions}
#' \item{V343}{Numeric; embedding vector dimensions}
#' \item{V344}{Numeric; embedding vector dimensions}
#' \item{V345}{Numeric; embedding vector dimensions}
#' \item{V346}{Numeric; embedding vector dimensions}
#' \item{V347}{Numeric; embedding vector dimensions}
#' \item{V348}{Numeric; embedding vector dimensions}
#' \item{V349}{Numeric; embedding vector dimensions}
#' \item{V350}{Numeric; embedding vector dimensions}
#' \item{V351}{Numeric; embedding vector dimensions}
#' \item{V352}{Numeric; embedding vector dimensions}
#' \item{V353}{Numeric; embedding vector dimensions}
#' \item{V354}{Numeric; embedding vector dimensions}
#' \item{V355}{Numeric; embedding vector dimensions}
#' \item{V356}{Numeric; embedding vector dimensions}
#' \item{V357}{Numeric; embedding vector dimensions}
#' \item{V358}{Numeric; embedding vector dimensions}
#' \item{V359}{Numeric; embedding vector dimensions}
#' \item{V360}{Numeric; embedding vector dimensions}
#' \item{V361}{Numeric; embedding vector dimensions}
#' \item{V362}{Numeric; embedding vector dimensions}
#' \item{V363}{Numeric; embedding vector dimensions}
#' \item{V364}{Numeric; embedding vector dimensions}
#' \item{V365}{Numeric; embedding vector dimensions}
#' \item{V366}{Numeric; embedding vector dimensions}
#' \item{V367}{Numeric; embedding vector dimensions}
#' \item{V368}{Numeric; embedding vector dimensions}
#' \item{V369}{Numeric; embedding vector dimensions}
#' \item{V370}{Numeric; embedding vector dimensions}
#' \item{V371}{Numeric; embedding vector dimensions}
#' \item{V372}{Numeric; embedding vector dimensions}
#' \item{V373}{Numeric; embedding vector dimensions}
#' \item{V374}{Numeric; embedding vector dimensions}
#' \item{V375}{Numeric; embedding vector dimensions}
#' \item{V376}{Numeric; embedding vector dimensions}
#' \item{V377}{Numeric; embedding vector dimensions}
#' \item{V378}{Numeric; embedding vector dimensions}
#' \item{V379}{Numeric; embedding vector dimensions}
#' \item{V380}{Numeric; embedding vector dimensions}
#' \item{V381}{Numeric; embedding vector dimensions}
#' \item{V382}{Numeric; embedding vector dimensions}
#' \item{V383}{Numeric; embedding vector dimensions}
#' \item{V384}{Numeric; embedding vector dimensions}
#' \item{V385}{Numeric; embedding vector dimensions}
#' \item{V386}{Numeric; embedding vector dimensions}
#' \item{V387}{Numeric; embedding vector dimensions}
#' \item{V388}{Numeric; embedding vector dimensions}
#' \item{V389}{Numeric; embedding vector dimensions}
#' \item{V390}{Numeric; embedding vector dimensions}
#' \item{V391}{Numeric; embedding vector dimensions}
#' \item{V392}{Numeric; embedding vector dimensions}
#' \item{V393}{Numeric; embedding vector dimensions}
#' \item{V394}{Numeric; embedding vector dimensions}
#' \item{V395}{Numeric; embedding vector dimensions}
#' \item{V396}{Numeric; embedding vector dimensions}
#' \item{V397}{Numeric; embedding vector dimensions}
#' \item{V398}{Numeric; embedding vector dimensions}
#' \item{V399}{Numeric; embedding vector dimensions}
#' \item{V400}{Numeric; embedding vector dimensions}
#' \item{V401}{Numeric; embedding vector dimensions}
#' \item{V402}{Numeric; embedding vector dimensions}
#' \item{V403}{Numeric; embedding vector dimensions}
#' \item{V404}{Numeric; embedding vector dimensions}
#' \item{V405}{Numeric; embedding vector dimensions}
#' \item{V406}{Numeric; embedding vector dimensions}
#' \item{V407}{Numeric; embedding vector dimensions}
#' \item{V408}{Numeric; embedding vector dimensions}
#' \item{V409}{Numeric; embedding vector dimensions}
#' \item{V410}{Numeric; embedding vector dimensions}
#' \item{V411}{Numeric; embedding vector dimensions}
#' \item{V412}{Numeric; embedding vector dimensions}
#' \item{V413}{Numeric; embedding vector dimensions}
#' \item{V414}{Numeric; embedding vector dimensions}
#' \item{V415}{Numeric; embedding vector dimensions}
#' \item{V416}{Numeric; embedding vector dimensions}
#' \item{V417}{Numeric; embedding vector dimensions}
#' \item{V418}{Numeric; embedding vector dimensions}
#' \item{V419}{Numeric; embedding vector dimensions}
#' \item{V420}{Numeric; embedding vector dimensions}
#' \item{V421}{Numeric; embedding vector dimensions}
#' \item{V422}{Numeric; embedding vector dimensions}
#' \item{V423}{Numeric; embedding vector dimensions}
#' \item{V424}{Numeric; embedding vector dimensions}
#' \item{V425}{Numeric; embedding vector dimensions}
#' \item{V426}{Numeric; embedding vector dimensions}
#' \item{V427}{Numeric; embedding vector dimensions}
#' \item{V428}{Numeric; embedding vector dimensions}
#' \item{V429}{Numeric; embedding vector dimensions}
#' \item{V430}{Numeric; embedding vector dimensions}
#' \item{V431}{Numeric; embedding vector dimensions}
#' \item{V432}{Numeric; embedding vector dimensions}
#' \item{V433}{Numeric; embedding vector dimensions}
#' \item{V434}{Numeric; embedding vector dimensions}
#' \item{V435}{Numeric; embedding vector dimensions}
#' \item{V436}{Numeric; embedding vector dimensions}
#' \item{V437}{Numeric; embedding vector dimensions}
#' \item{V438}{Numeric; embedding vector dimensions}
#' \item{V439}{Numeric; embedding vector dimensions}
#' \item{V440}{Numeric; embedding vector dimensions}
#' \item{V441}{Numeric; embedding vector dimensions}
#' \item{V442}{Numeric; embedding vector dimensions}
#' \item{V443}{Numeric; embedding vector dimensions}
#' \item{V444}{Numeric; embedding vector dimensions}
#' \item{V445}{Numeric; embedding vector dimensions}
#' \item{V446}{Numeric; embedding vector dimensions}
#' \item{V447}{Numeric; embedding vector dimensions}
#' \item{V448}{Numeric; embedding vector dimensions}
#' \item{V449}{Numeric; embedding vector dimensions}
#' \item{V450}{Numeric; embedding vector dimensions}
#' \item{V451}{Numeric; embedding vector dimensions}
#' \item{V452}{Numeric; embedding vector dimensions}
#' \item{V453}{Numeric; embedding vector dimensions}
#' \item{V454}{Numeric; embedding vector dimensions}
#' \item{V455}{Numeric; embedding vector dimensions}
#' \item{V456}{Numeric; embedding vector dimensions}
#' \item{V457}{Numeric; embedding vector dimensions}
#' \item{V458}{Numeric; embedding vector dimensions}
#' \item{V459}{Numeric; embedding vector dimensions}
#' \item{V460}{Numeric; embedding vector dimensions}
#' \item{V461}{Numeric; embedding vector dimensions}
#' \item{V462}{Numeric; embedding vector dimensions}
#' \item{V463}{Numeric; embedding vector dimensions}
#' \item{V464}{Numeric; embedding vector dimensions}
#' \item{V465}{Numeric; embedding vector dimensions}
#' \item{V466}{Numeric; embedding vector dimensions}
#' \item{V467}{Numeric; embedding vector dimensions}
#' \item{V468}{Numeric; embedding vector dimensions}
#' \item{V469}{Numeric; embedding vector dimensions}
#' \item{V470}{Numeric; embedding vector dimensions}
#' \item{V471}{Numeric; embedding vector dimensions}
#' \item{V472}{Numeric; embedding vector dimensions}
#' \item{V473}{Numeric; embedding vector dimensions}
#' \item{V474}{Numeric; embedding vector dimensions}
#' \item{V475}{Numeric; embedding vector dimensions}
#' \item{V476}{Numeric; embedding vector dimensions}
#' \item{V477}{Numeric; embedding vector dimensions}
#' \item{V478}{Numeric; embedding vector dimensions}
#' \item{V479}{Numeric; embedding vector dimensions}
#' \item{V480}{Numeric; embedding vector dimensions}
#' \item{V481}{Numeric; embedding vector dimensions}
#' \item{V482}{Numeric; embedding vector dimensions}
#' \item{V483}{Numeric; embedding vector dimensions}
#' \item{V484}{Numeric; embedding vector dimensions}
#' \item{V485}{Numeric; embedding vector dimensions}
#' \item{V486}{Numeric; embedding vector dimensions}
#' \item{V487}{Numeric; embedding vector dimensions}
#' \item{V488}{Numeric; embedding vector dimensions}
#' \item{V489}{Numeric; embedding vector dimensions}
#' \item{V490}{Numeric; embedding vector dimensions}
#' \item{V491}{Numeric; embedding vector dimensions}
#' \item{V492}{Numeric; embedding vector dimensions}
#' \item{V493}{Numeric; embedding vector dimensions}
#' \item{V494}{Numeric; embedding vector dimensions}
#' \item{V495}{Numeric; embedding vector dimensions}
#' \item{V496}{Numeric; embedding vector dimensions}
#' \item{V497}{Numeric; embedding vector dimensions}
#' \item{V498}{Numeric; embedding vector dimensions}
#' \item{V499}{Numeric; embedding vector dimensions}
#' \item{V500}{Numeric; embedding vector dimensions}
#' \item{V501}{Numeric; embedding vector dimensions}
#' \item{V502}{Numeric; embedding vector dimensions}
#' \item{V503}{Numeric; embedding vector dimensions}
#' \item{V504}{Numeric; embedding vector dimensions}
#' \item{V505}{Numeric; embedding vector dimensions}
#' \item{V506}{Numeric; embedding vector dimensions}
#' \item{V507}{Numeric; embedding vector dimensions}
#' \item{V508}{Numeric; embedding vector dimensions}
#' \item{V509}{Numeric; embedding vector dimensions}
#' \item{V510}{Numeric; embedding vector dimensions}
#' \item{V511}{Numeric; embedding vector dimensions}
#' \item{V512}{Numeric; embedding vector dimensions}
#' \item{V513}{Numeric; embedding vector dimensions}
#' \item{V514}{Numeric; embedding vector dimensions}
#' \item{V515}{Numeric; embedding vector dimensions}
#' \item{V516}{Numeric; embedding vector dimensions}
#' \item{V517}{Numeric; embedding vector dimensions}
#' \item{V518}{Numeric; embedding vector dimensions}
#' \item{V519}{Numeric; embedding vector dimensions}
#' \item{V520}{Numeric; embedding vector dimensions}
#' \item{V521}{Numeric; embedding vector dimensions}
#' \item{V522}{Numeric; embedding vector dimensions}
#' \item{V523}{Numeric; embedding vector dimensions}
#' \item{V524}{Numeric; embedding vector dimensions}
#' \item{V525}{Numeric; embedding vector dimensions}
#' \item{V526}{Numeric; embedding vector dimensions}
#' \item{V527}{Numeric; embedding vector dimensions}
#' \item{V528}{Numeric; embedding vector dimensions}
#' \item{V529}{Numeric; embedding vector dimensions}
#' \item{V530}{Numeric; embedding vector dimensions}
#' \item{V531}{Numeric; embedding vector dimensions}
#' \item{V532}{Numeric; embedding vector dimensions}
#' \item{V533}{Numeric; embedding vector dimensions}
#' \item{V534}{Numeric; embedding vector dimensions}
#' \item{V535}{Numeric; embedding vector dimensions}
#' \item{V536}{Numeric; embedding vector dimensions}
#' \item{V537}{Numeric; embedding vector dimensions}
#' \item{V538}{Numeric; embedding vector dimensions}
#' \item{V539}{Numeric; embedding vector dimensions}
#' \item{V540}{Numeric; embedding vector dimensions}
#' \item{V541}{Numeric; embedding vector dimensions}
#' \item{V542}{Numeric; embedding vector dimensions}
#' \item{V543}{Numeric; embedding vector dimensions}
#' \item{V544}{Numeric; embedding vector dimensions}
#' \item{V545}{Numeric; embedding vector dimensions}
#' \item{V546}{Numeric; embedding vector dimensions}
#' \item{V547}{Numeric; embedding vector dimensions}
#' \item{V548}{Numeric; embedding vector dimensions}
#' \item{V549}{Numeric; embedding vector dimensions}
#' \item{V550}{Numeric; embedding vector dimensions}
#' \item{V551}{Numeric; embedding vector dimensions}
#' \item{V552}{Numeric; embedding vector dimensions}
#' \item{V553}{Numeric; embedding vector dimensions}
#' \item{V554}{Numeric; embedding vector dimensions}
#' \item{V555}{Numeric; embedding vector dimensions}
#' \item{V556}{Numeric; embedding vector dimensions}
#' \item{V557}{Numeric; embedding vector dimensions}
#' \item{V558}{Numeric; embedding vector dimensions}
#' \item{V559}{Numeric; embedding vector dimensions}
#' \item{V560}{Numeric; embedding vector dimensions}
#' \item{V561}{Numeric; embedding vector dimensions}
#' \item{V562}{Numeric; embedding vector dimensions}
#' \item{V563}{Numeric; embedding vector dimensions}
#' \item{V564}{Numeric; embedding vector dimensions}
#' \item{V565}{Numeric; embedding vector dimensions}
#' \item{V566}{Numeric; embedding vector dimensions}
#' \item{V567}{Numeric; embedding vector dimensions}
#' \item{V568}{Numeric; embedding vector dimensions}
#' \item{V569}{Numeric; embedding vector dimensions}
#' \item{V570}{Numeric; embedding vector dimensions}
#' \item{V571}{Numeric; embedding vector dimensions}
#' \item{V572}{Numeric; embedding vector dimensions}
#' \item{V573}{Numeric; embedding vector dimensions}
#' \item{V574}{Numeric; embedding vector dimensions}
#' \item{V575}{Numeric; embedding vector dimensions}
#' \item{V576}{Numeric; embedding vector dimensions}
#' \item{V577}{Numeric; embedding vector dimensions}
#' \item{V578}{Numeric; embedding vector dimensions}
#' \item{V579}{Numeric; embedding vector dimensions}
#' \item{V580}{Numeric; embedding vector dimensions}
#' \item{V581}{Numeric; embedding vector dimensions}
#' \item{V582}{Numeric; embedding vector dimensions}
#' \item{V583}{Numeric; embedding vector dimensions}
#' \item{V584}{Numeric; embedding vector dimensions}
#' \item{V585}{Numeric; embedding vector dimensions}
#' \item{V586}{Numeric; embedding vector dimensions}
#' \item{V587}{Numeric; embedding vector dimensions}
#' \item{V588}{Numeric; embedding vector dimensions}
#' \item{V589}{Numeric; embedding vector dimensions}
#' \item{V590}{Numeric; embedding vector dimensions}
#' \item{V591}{Numeric; embedding vector dimensions}
#' \item{V592}{Numeric; embedding vector dimensions}
#' \item{V593}{Numeric; embedding vector dimensions}
#' \item{V594}{Numeric; embedding vector dimensions}
#' \item{V595}{Numeric; embedding vector dimensions}
#' \item{V596}{Numeric; embedding vector dimensions}
#' \item{V597}{Numeric; embedding vector dimensions}
#' \item{V598}{Numeric; embedding vector dimensions}
#' \item{V599}{Numeric; embedding vector dimensions}
#' \item{V600}{Numeric; embedding vector dimensions}
#' \item{V601}{Numeric; embedding vector dimensions}
#' \item{V602}{Numeric; embedding vector dimensions}
#' \item{V603}{Numeric; embedding vector dimensions}
#' \item{V604}{Numeric; embedding vector dimensions}
#' \item{V605}{Numeric; embedding vector dimensions}
#' \item{V606}{Numeric; embedding vector dimensions}
#' \item{V607}{Numeric; embedding vector dimensions}
#' \item{V608}{Numeric; embedding vector dimensions}
#' \item{V609}{Numeric; embedding vector dimensions}
#' \item{V610}{Numeric; embedding vector dimensions}
#' \item{V611}{Numeric; embedding vector dimensions}
#' \item{V612}{Numeric; embedding vector dimensions}
#' \item{V613}{Numeric; embedding vector dimensions}
#' \item{V614}{Numeric; embedding vector dimensions}
#' \item{V615}{Numeric; embedding vector dimensions}
#' \item{V616}{Numeric; embedding vector dimensions}
#' \item{V617}{Numeric; embedding vector dimensions}
#' \item{V618}{Numeric; embedding vector dimensions}
#' \item{V619}{Numeric; embedding vector dimensions}
#' \item{V620}{Numeric; embedding vector dimensions}
#' \item{V621}{Numeric; embedding vector dimensions}
#' \item{V622}{Numeric; embedding vector dimensions}
#' \item{V623}{Numeric; embedding vector dimensions}
#' \item{V624}{Numeric; embedding vector dimensions}
#' \item{V625}{Numeric; embedding vector dimensions}
#' \item{V626}{Numeric; embedding vector dimensions}
#' \item{V627}{Numeric; embedding vector dimensions}
#' \item{V628}{Numeric; embedding vector dimensions}
#' \item{V629}{Numeric; embedding vector dimensions}
#' \item{V630}{Numeric; embedding vector dimensions}
#' \item{V631}{Numeric; embedding vector dimensions}
#' \item{V632}{Numeric; embedding vector dimensions}
#' \item{V633}{Numeric; embedding vector dimensions}
#' \item{V634}{Numeric; embedding vector dimensions}
#' \item{V635}{Numeric; embedding vector dimensions}
#' \item{V636}{Numeric; embedding vector dimensions}
#' \item{V637}{Numeric; embedding vector dimensions}
#' \item{V638}{Numeric; embedding vector dimensions}
#' \item{V639}{Numeric; embedding vector dimensions}
#' \item{V640}{Numeric; embedding vector dimensions}
#' \item{V641}{Numeric; embedding vector dimensions}
#' \item{V642}{Numeric; embedding vector dimensions}
#' \item{V643}{Numeric; embedding vector dimensions}
#' \item{V644}{Numeric; embedding vector dimensions}
#' \item{V645}{Numeric; embedding vector dimensions}
#' \item{V646}{Numeric; embedding vector dimensions}
#' \item{V647}{Numeric; embedding vector dimensions}
#' \item{V648}{Numeric; embedding vector dimensions}
#' \item{V649}{Numeric; embedding vector dimensions}
#' \item{V650}{Numeric; embedding vector dimensions}
#' \item{V651}{Numeric; embedding vector dimensions}
#' \item{V652}{Numeric; embedding vector dimensions}
#' \item{V653}{Numeric; embedding vector dimensions}
#' \item{V654}{Numeric; embedding vector dimensions}
#' \item{V655}{Numeric; embedding vector dimensions}
#' \item{V656}{Numeric; embedding vector dimensions}
#' \item{V657}{Numeric; embedding vector dimensions}
#' \item{V658}{Numeric; embedding vector dimensions}
#' \item{V659}{Numeric; embedding vector dimensions}
#' \item{V660}{Numeric; embedding vector dimensions}
#' \item{V661}{Numeric; embedding vector dimensions}
#' \item{V662}{Numeric; embedding vector dimensions}
#' \item{V663}{Numeric; embedding vector dimensions}
#' \item{V664}{Numeric; embedding vector dimensions}
#' \item{V665}{Numeric; embedding vector dimensions}
#' \item{V666}{Numeric; embedding vector dimensions}
#' \item{V667}{Numeric; embedding vector dimensions}
#' \item{V668}{Numeric; embedding vector dimensions}
#' \item{V669}{Numeric; embedding vector dimensions}
#' \item{V670}{Numeric; embedding vector dimensions}
#' \item{V671}{Numeric; embedding vector dimensions}
#' \item{V672}{Numeric; embedding vector dimensions}
#' \item{V673}{Numeric; embedding vector dimensions}
#' \item{V674}{Numeric; embedding vector dimensions}
#' \item{V675}{Numeric; embedding vector dimensions}
#' \item{V676}{Numeric; embedding vector dimensions}
#' \item{V677}{Numeric; embedding vector dimensions}
#' \item{V678}{Numeric; embedding vector dimensions}
#' \item{V679}{Numeric; embedding vector dimensions}
#' \item{V680}{Numeric; embedding vector dimensions}
#' \item{V681}{Numeric; embedding vector dimensions}
#' \item{V682}{Numeric; embedding vector dimensions}
#' \item{V683}{Numeric; embedding vector dimensions}
#' \item{V684}{Numeric; embedding vector dimensions}
#' \item{V685}{Numeric; embedding vector dimensions}
#' \item{V686}{Numeric; embedding vector dimensions}
#' \item{V687}{Numeric; embedding vector dimensions}
#' \item{V688}{Numeric; embedding vector dimensions}
#' \item{V689}{Numeric; embedding vector dimensions}
#' \item{V690}{Numeric; embedding vector dimensions}
#' \item{V691}{Numeric; embedding vector dimensions}
#' \item{V692}{Numeric; embedding vector dimensions}
#' \item{V693}{Numeric; embedding vector dimensions}
#' \item{V694}{Numeric; embedding vector dimensions}
#' \item{V695}{Numeric; embedding vector dimensions}
#' \item{V696}{Numeric; embedding vector dimensions}
#' \item{V697}{Numeric; embedding vector dimensions}
#' \item{V698}{Numeric; embedding vector dimensions}
#' \item{V699}{Numeric; embedding vector dimensions}
#' \item{V700}{Numeric; embedding vector dimensions}
#' \item{V701}{Numeric; embedding vector dimensions}
#' \item{V702}{Numeric; embedding vector dimensions}
#' \item{V703}{Numeric; embedding vector dimensions}
#' \item{V704}{Numeric; embedding vector dimensions}
#' \item{V705}{Numeric; embedding vector dimensions}
#' \item{V706}{Numeric; embedding vector dimensions}
#' \item{V707}{Numeric; embedding vector dimensions}
#' \item{V708}{Numeric; embedding vector dimensions}
#' \item{V709}{Numeric; embedding vector dimensions}
#' \item{V710}{Numeric; embedding vector dimensions}
#' \item{V711}{Numeric; embedding vector dimensions}
#' \item{V712}{Numeric; embedding vector dimensions}
#' \item{V713}{Numeric; embedding vector dimensions}
#' \item{V714}{Numeric; embedding vector dimensions}
#' \item{V715}{Numeric; embedding vector dimensions}
#' \item{V716}{Numeric; embedding vector dimensions}
#' \item{V717}{Numeric; embedding vector dimensions}
#' \item{V718}{Numeric; embedding vector dimensions}
#' \item{V719}{Numeric; embedding vector dimensions}
#' \item{V720}{Numeric; embedding vector dimensions}
#' \item{V721}{Numeric; embedding vector dimensions}
#' \item{V722}{Numeric; embedding vector dimensions}
#' \item{V723}{Numeric; embedding vector dimensions}
#' \item{V724}{Numeric; embedding vector dimensions}
#' \item{V725}{Numeric; embedding vector dimensions}
#' \item{V726}{Numeric; embedding vector dimensions}
#' \item{V727}{Numeric; embedding vector dimensions}
#' \item{V728}{Numeric; embedding vector dimensions}
#' \item{V729}{Numeric; embedding vector dimensions}
#' \item{V730}{Numeric; embedding vector dimensions}
#' \item{V731}{Numeric; embedding vector dimensions}
#' \item{V732}{Numeric; embedding vector dimensions}
#' \item{V733}{Numeric; embedding vector dimensions}
#' \item{V734}{Numeric; embedding vector dimensions}
#' \item{V735}{Numeric; embedding vector dimensions}
#' \item{V736}{Numeric; embedding vector dimensions}
#' \item{V737}{Numeric; embedding vector dimensions}
#' \item{V738}{Numeric; embedding vector dimensions}
#' \item{V739}{Numeric; embedding vector dimensions}
#' \item{V740}{Numeric; embedding vector dimensions}
#' \item{V741}{Numeric; embedding vector dimensions}
#' \item{V742}{Numeric; embedding vector dimensions}
#' \item{V743}{Numeric; embedding vector dimensions}
#' \item{V744}{Numeric; embedding vector dimensions}
#' \item{V745}{Numeric; embedding vector dimensions}
#' \item{V746}{Numeric; embedding vector dimensions}
#' \item{V747}{Numeric; embedding vector dimensions}
#' \item{V748}{Numeric; embedding vector dimensions}
#' \item{V749}{Numeric; embedding vector dimensions}
#' \item{V750}{Numeric; embedding vector dimensions}
#' \item{V751}{Numeric; embedding vector dimensions}
#' \item{V752}{Numeric; embedding vector dimensions}
#' \item{V753}{Numeric; embedding vector dimensions}
#' \item{V754}{Numeric; embedding vector dimensions}
#' \item{V755}{Numeric; embedding vector dimensions}
#' \item{V756}{Numeric; embedding vector dimensions}
#' \item{V757}{Numeric; embedding vector dimensions}
#' \item{V758}{Numeric; embedding vector dimensions}
#' \item{V759}{Numeric; embedding vector dimensions}
#' \item{V760}{Numeric; embedding vector dimensions}
#' \item{V761}{Numeric; embedding vector dimensions}
#' \item{V762}{Numeric; embedding vector dimensions}
#' \item{V763}{Numeric; embedding vector dimensions}
#' \item{V764}{Numeric; embedding vector dimensions}
#' \item{V765}{Numeric; embedding vector dimensions}
#' \item{V766}{Numeric; embedding vector dimensions}
#' \item{V767}{Numeric; embedding vector dimensions}
#' \item{V768}{Numeric; embedding vector dimensions}
#' }
#' @source Generated using Hugging Face embedding model via EndpointR functions
"df_embeddings_hf"

#' Example sentiment classification results from Hugging Face API
#'
#' A sample dataset containing sentiment classification results generated using
#' Hugging Face's classification API. This dataset demonstrates the structure
#' of results returned by the `hf_classify_batch()` and `hf_classify_df()` functions.
#'
#' @format A data frame with 3 rows and 7 variables:
#' \describe{
#'   \item{id}{Integer; unique identifier for each text}
#'   \item{text}{Character; the original text that was classified}
#'   \item{category}{Character; category classification of the text}
#'   \item{NEGATIVE}{Numeric; probability score for negative sentiment (0-1)}
#'   \item{POSITIVE}{Numeric; probability score for positive sentiment (0-1)}
#'   \item{.error}{Logical; whether the classification process failed}
#'   \item{.error_msg}{Character; error message if classification failed (NA if successful)}
#' }
#' @source Generated using Hugging Face sentiment classification model via EndpointR functions
"df_sentiment_classification_example"

#' Single sentiment classification result example
#'
#' A sample result from sentiment classification of a single text using
#' Hugging Face's classification API. This demonstrates the structure
#' returned by the `hf_classify_text()` function.
#'
#' @format A data frame with 1 row and 2 variables:
#' \describe{
#'   \item{NEGATIVE}{Numeric; probability score for negative sentiment (0-1)}
#'   \item{POSITIVE}{Numeric; probability score for positive sentiment (0-1)}
#' }
#' @source Generated using Hugging Face sentiment classification model via EndpointR functions
"sentiment_classification_example"

#' Single embedding result example from Hugging Face API
#'
#' A sample embedding vector result from processing a single text using
#' Hugging Face's embedding API. This demonstrates the structure returned
#' by the `hf_embed_text()` function.
#'
#' @format A data frame with 1 row and 768 variables:
#' \describe{
#' \item{V1}{Numeric; embedding vector dimensions}
#' \item{V2}{Numeric; embedding vector dimensions}
#' \item{V3}{Numeric; embedding vector dimensions}
#' \item{V4}{Numeric; embedding vector dimensions}
#' \item{V5}{Numeric; embedding vector dimensions}
#' \item{V6}{Numeric; embedding vector dimensions}
#' \item{V7}{Numeric; embedding vector dimensions}
#' \item{V8}{Numeric; embedding vector dimensions}
#' \item{V9}{Numeric; embedding vector dimensions}
#' \item{V10}{Numeric; embedding vector dimensions}
#' \item{V11}{Numeric; embedding vector dimensions}
#' \item{V12}{Numeric; embedding vector dimensions}
#' \item{V13}{Numeric; embedding vector dimensions}
#' \item{V14}{Numeric; embedding vector dimensions}
#' \item{V15}{Numeric; embedding vector dimensions}
#' \item{V16}{Numeric; embedding vector dimensions}
#' \item{V17}{Numeric; embedding vector dimensions}
#' \item{V18}{Numeric; embedding vector dimensions}
#' \item{V19}{Numeric; embedding vector dimensions}
#' \item{V20}{Numeric; embedding vector dimensions}
#' \item{V21}{Numeric; embedding vector dimensions}
#' \item{V22}{Numeric; embedding vector dimensions}
#' \item{V23}{Numeric; embedding vector dimensions}
#' \item{V24}{Numeric; embedding vector dimensions}
#' \item{V25}{Numeric; embedding vector dimensions}
#' \item{V26}{Numeric; embedding vector dimensions}
#' \item{V27}{Numeric; embedding vector dimensions}
#' \item{V28}{Numeric; embedding vector dimensions}
#' \item{V29}{Numeric; embedding vector dimensions}
#' \item{V30}{Numeric; embedding vector dimensions}
#' \item{V31}{Numeric; embedding vector dimensions}
#' \item{V32}{Numeric; embedding vector dimensions}
#' \item{V33}{Numeric; embedding vector dimensions}
#' \item{V34}{Numeric; embedding vector dimensions}
#' \item{V35}{Numeric; embedding vector dimensions}
#' \item{V36}{Numeric; embedding vector dimensions}
#' \item{V37}{Numeric; embedding vector dimensions}
#' \item{V38}{Numeric; embedding vector dimensions}
#' \item{V39}{Numeric; embedding vector dimensions}
#' \item{V40}{Numeric; embedding vector dimensions}
#' \item{V41}{Numeric; embedding vector dimensions}
#' \item{V42}{Numeric; embedding vector dimensions}
#' \item{V43}{Numeric; embedding vector dimensions}
#' \item{V44}{Numeric; embedding vector dimensions}
#' \item{V45}{Numeric; embedding vector dimensions}
#' \item{V46}{Numeric; embedding vector dimensions}
#' \item{V47}{Numeric; embedding vector dimensions}
#' \item{V48}{Numeric; embedding vector dimensions}
#' \item{V49}{Numeric; embedding vector dimensions}
#' \item{V50}{Numeric; embedding vector dimensions}
#' \item{V51}{Numeric; embedding vector dimensions}
#' \item{V52}{Numeric; embedding vector dimensions}
#' \item{V53}{Numeric; embedding vector dimensions}
#' \item{V54}{Numeric; embedding vector dimensions}
#' \item{V55}{Numeric; embedding vector dimensions}
#' \item{V56}{Numeric; embedding vector dimensions}
#' \item{V57}{Numeric; embedding vector dimensions}
#' \item{V58}{Numeric; embedding vector dimensions}
#' \item{V59}{Numeric; embedding vector dimensions}
#' \item{V60}{Numeric; embedding vector dimensions}
#' \item{V61}{Numeric; embedding vector dimensions}
#' \item{V62}{Numeric; embedding vector dimensions}
#' \item{V63}{Numeric; embedding vector dimensions}
#' \item{V64}{Numeric; embedding vector dimensions}
#' \item{V65}{Numeric; embedding vector dimensions}
#' \item{V66}{Numeric; embedding vector dimensions}
#' \item{V67}{Numeric; embedding vector dimensions}
#' \item{V68}{Numeric; embedding vector dimensions}
#' \item{V69}{Numeric; embedding vector dimensions}
#' \item{V70}{Numeric; embedding vector dimensions}
#' \item{V71}{Numeric; embedding vector dimensions}
#' \item{V72}{Numeric; embedding vector dimensions}
#' \item{V73}{Numeric; embedding vector dimensions}
#' \item{V74}{Numeric; embedding vector dimensions}
#' \item{V75}{Numeric; embedding vector dimensions}
#' \item{V76}{Numeric; embedding vector dimensions}
#' \item{V77}{Numeric; embedding vector dimensions}
#' \item{V78}{Numeric; embedding vector dimensions}
#' \item{V79}{Numeric; embedding vector dimensions}
#' \item{V80}{Numeric; embedding vector dimensions}
#' \item{V81}{Numeric; embedding vector dimensions}
#' \item{V82}{Numeric; embedding vector dimensions}
#' \item{V83}{Numeric; embedding vector dimensions}
#' \item{V84}{Numeric; embedding vector dimensions}
#' \item{V85}{Numeric; embedding vector dimensions}
#' \item{V86}{Numeric; embedding vector dimensions}
#' \item{V87}{Numeric; embedding vector dimensions}
#' \item{V88}{Numeric; embedding vector dimensions}
#' \item{V89}{Numeric; embedding vector dimensions}
#' \item{V90}{Numeric; embedding vector dimensions}
#' \item{V91}{Numeric; embedding vector dimensions}
#' \item{V92}{Numeric; embedding vector dimensions}
#' \item{V93}{Numeric; embedding vector dimensions}
#' \item{V94}{Numeric; embedding vector dimensions}
#' \item{V95}{Numeric; embedding vector dimensions}
#' \item{V96}{Numeric; embedding vector dimensions}
#' \item{V97}{Numeric; embedding vector dimensions}
#' \item{V98}{Numeric; embedding vector dimensions}
#' \item{V99}{Numeric; embedding vector dimensions}
#' \item{V100}{Numeric; embedding vector dimensions}
#' \item{V101}{Numeric; embedding vector dimensions}
#' \item{V102}{Numeric; embedding vector dimensions}
#' \item{V103}{Numeric; embedding vector dimensions}
#' \item{V104}{Numeric; embedding vector dimensions}
#' \item{V105}{Numeric; embedding vector dimensions}
#' \item{V106}{Numeric; embedding vector dimensions}
#' \item{V107}{Numeric; embedding vector dimensions}
#' \item{V108}{Numeric; embedding vector dimensions}
#' \item{V109}{Numeric; embedding vector dimensions}
#' \item{V110}{Numeric; embedding vector dimensions}
#' \item{V111}{Numeric; embedding vector dimensions}
#' \item{V112}{Numeric; embedding vector dimensions}
#' \item{V113}{Numeric; embedding vector dimensions}
#' \item{V114}{Numeric; embedding vector dimensions}
#' \item{V115}{Numeric; embedding vector dimensions}
#' \item{V116}{Numeric; embedding vector dimensions}
#' \item{V117}{Numeric; embedding vector dimensions}
#' \item{V118}{Numeric; embedding vector dimensions}
#' \item{V119}{Numeric; embedding vector dimensions}
#' \item{V120}{Numeric; embedding vector dimensions}
#' \item{V121}{Numeric; embedding vector dimensions}
#' \item{V122}{Numeric; embedding vector dimensions}
#' \item{V123}{Numeric; embedding vector dimensions}
#' \item{V124}{Numeric; embedding vector dimensions}
#' \item{V125}{Numeric; embedding vector dimensions}
#' \item{V126}{Numeric; embedding vector dimensions}
#' \item{V127}{Numeric; embedding vector dimensions}
#' \item{V128}{Numeric; embedding vector dimensions}
#' \item{V129}{Numeric; embedding vector dimensions}
#' \item{V130}{Numeric; embedding vector dimensions}
#' \item{V131}{Numeric; embedding vector dimensions}
#' \item{V132}{Numeric; embedding vector dimensions}
#' \item{V133}{Numeric; embedding vector dimensions}
#' \item{V134}{Numeric; embedding vector dimensions}
#' \item{V135}{Numeric; embedding vector dimensions}
#' \item{V136}{Numeric; embedding vector dimensions}
#' \item{V137}{Numeric; embedding vector dimensions}
#' \item{V138}{Numeric; embedding vector dimensions}
#' \item{V139}{Numeric; embedding vector dimensions}
#' \item{V140}{Numeric; embedding vector dimensions}
#' \item{V141}{Numeric; embedding vector dimensions}
#' \item{V142}{Numeric; embedding vector dimensions}
#' \item{V143}{Numeric; embedding vector dimensions}
#' \item{V144}{Numeric; embedding vector dimensions}
#' \item{V145}{Numeric; embedding vector dimensions}
#' \item{V146}{Numeric; embedding vector dimensions}
#' \item{V147}{Numeric; embedding vector dimensions}
#' \item{V148}{Numeric; embedding vector dimensions}
#' \item{V149}{Numeric; embedding vector dimensions}
#' \item{V150}{Numeric; embedding vector dimensions}
#' \item{V151}{Numeric; embedding vector dimensions}
#' \item{V152}{Numeric; embedding vector dimensions}
#' \item{V153}{Numeric; embedding vector dimensions}
#' \item{V154}{Numeric; embedding vector dimensions}
#' \item{V155}{Numeric; embedding vector dimensions}
#' \item{V156}{Numeric; embedding vector dimensions}
#' \item{V157}{Numeric; embedding vector dimensions}
#' \item{V158}{Numeric; embedding vector dimensions}
#' \item{V159}{Numeric; embedding vector dimensions}
#' \item{V160}{Numeric; embedding vector dimensions}
#' \item{V161}{Numeric; embedding vector dimensions}
#' \item{V162}{Numeric; embedding vector dimensions}
#' \item{V163}{Numeric; embedding vector dimensions}
#' \item{V164}{Numeric; embedding vector dimensions}
#' \item{V165}{Numeric; embedding vector dimensions}
#' \item{V166}{Numeric; embedding vector dimensions}
#' \item{V167}{Numeric; embedding vector dimensions}
#' \item{V168}{Numeric; embedding vector dimensions}
#' \item{V169}{Numeric; embedding vector dimensions}
#' \item{V170}{Numeric; embedding vector dimensions}
#' \item{V171}{Numeric; embedding vector dimensions}
#' \item{V172}{Numeric; embedding vector dimensions}
#' \item{V173}{Numeric; embedding vector dimensions}
#' \item{V174}{Numeric; embedding vector dimensions}
#' \item{V175}{Numeric; embedding vector dimensions}
#' \item{V176}{Numeric; embedding vector dimensions}
#' \item{V177}{Numeric; embedding vector dimensions}
#' \item{V178}{Numeric; embedding vector dimensions}
#' \item{V179}{Numeric; embedding vector dimensions}
#' \item{V180}{Numeric; embedding vector dimensions}
#' \item{V181}{Numeric; embedding vector dimensions}
#' \item{V182}{Numeric; embedding vector dimensions}
#' \item{V183}{Numeric; embedding vector dimensions}
#' \item{V184}{Numeric; embedding vector dimensions}
#' \item{V185}{Numeric; embedding vector dimensions}
#' \item{V186}{Numeric; embedding vector dimensions}
#' \item{V187}{Numeric; embedding vector dimensions}
#' \item{V188}{Numeric; embedding vector dimensions}
#' \item{V189}{Numeric; embedding vector dimensions}
#' \item{V190}{Numeric; embedding vector dimensions}
#' \item{V191}{Numeric; embedding vector dimensions}
#' \item{V192}{Numeric; embedding vector dimensions}
#' \item{V193}{Numeric; embedding vector dimensions}
#' \item{V194}{Numeric; embedding vector dimensions}
#' \item{V195}{Numeric; embedding vector dimensions}
#' \item{V196}{Numeric; embedding vector dimensions}
#' \item{V197}{Numeric; embedding vector dimensions}
#' \item{V198}{Numeric; embedding vector dimensions}
#' \item{V199}{Numeric; embedding vector dimensions}
#' \item{V200}{Numeric; embedding vector dimensions}
#' \item{V201}{Numeric; embedding vector dimensions}
#' \item{V202}{Numeric; embedding vector dimensions}
#' \item{V203}{Numeric; embedding vector dimensions}
#' \item{V204}{Numeric; embedding vector dimensions}
#' \item{V205}{Numeric; embedding vector dimensions}
#' \item{V206}{Numeric; embedding vector dimensions}
#' \item{V207}{Numeric; embedding vector dimensions}
#' \item{V208}{Numeric; embedding vector dimensions}
#' \item{V209}{Numeric; embedding vector dimensions}
#' \item{V210}{Numeric; embedding vector dimensions}
#' \item{V211}{Numeric; embedding vector dimensions}
#' \item{V212}{Numeric; embedding vector dimensions}
#' \item{V213}{Numeric; embedding vector dimensions}
#' \item{V214}{Numeric; embedding vector dimensions}
#' \item{V215}{Numeric; embedding vector dimensions}
#' \item{V216}{Numeric; embedding vector dimensions}
#' \item{V217}{Numeric; embedding vector dimensions}
#' \item{V218}{Numeric; embedding vector dimensions}
#' \item{V219}{Numeric; embedding vector dimensions}
#' \item{V220}{Numeric; embedding vector dimensions}
#' \item{V221}{Numeric; embedding vector dimensions}
#' \item{V222}{Numeric; embedding vector dimensions}
#' \item{V223}{Numeric; embedding vector dimensions}
#' \item{V224}{Numeric; embedding vector dimensions}
#' \item{V225}{Numeric; embedding vector dimensions}
#' \item{V226}{Numeric; embedding vector dimensions}
#' \item{V227}{Numeric; embedding vector dimensions}
#' \item{V228}{Numeric; embedding vector dimensions}
#' \item{V229}{Numeric; embedding vector dimensions}
#' \item{V230}{Numeric; embedding vector dimensions}
#' \item{V231}{Numeric; embedding vector dimensions}
#' \item{V232}{Numeric; embedding vector dimensions}
#' \item{V233}{Numeric; embedding vector dimensions}
#' \item{V234}{Numeric; embedding vector dimensions}
#' \item{V235}{Numeric; embedding vector dimensions}
#' \item{V236}{Numeric; embedding vector dimensions}
#' \item{V237}{Numeric; embedding vector dimensions}
#' \item{V238}{Numeric; embedding vector dimensions}
#' \item{V239}{Numeric; embedding vector dimensions}
#' \item{V240}{Numeric; embedding vector dimensions}
#' \item{V241}{Numeric; embedding vector dimensions}
#' \item{V242}{Numeric; embedding vector dimensions}
#' \item{V243}{Numeric; embedding vector dimensions}
#' \item{V244}{Numeric; embedding vector dimensions}
#' \item{V245}{Numeric; embedding vector dimensions}
#' \item{V246}{Numeric; embedding vector dimensions}
#' \item{V247}{Numeric; embedding vector dimensions}
#' \item{V248}{Numeric; embedding vector dimensions}
#' \item{V249}{Numeric; embedding vector dimensions}
#' \item{V250}{Numeric; embedding vector dimensions}
#' \item{V251}{Numeric; embedding vector dimensions}
#' \item{V252}{Numeric; embedding vector dimensions}
#' \item{V253}{Numeric; embedding vector dimensions}
#' \item{V254}{Numeric; embedding vector dimensions}
#' \item{V255}{Numeric; embedding vector dimensions}
#' \item{V256}{Numeric; embedding vector dimensions}
#' \item{V257}{Numeric; embedding vector dimensions}
#' \item{V258}{Numeric; embedding vector dimensions}
#' \item{V259}{Numeric; embedding vector dimensions}
#' \item{V260}{Numeric; embedding vector dimensions}
#' \item{V261}{Numeric; embedding vector dimensions}
#' \item{V262}{Numeric; embedding vector dimensions}
#' \item{V263}{Numeric; embedding vector dimensions}
#' \item{V264}{Numeric; embedding vector dimensions}
#' \item{V265}{Numeric; embedding vector dimensions}
#' \item{V266}{Numeric; embedding vector dimensions}
#' \item{V267}{Numeric; embedding vector dimensions}
#' \item{V268}{Numeric; embedding vector dimensions}
#' \item{V269}{Numeric; embedding vector dimensions}
#' \item{V270}{Numeric; embedding vector dimensions}
#' \item{V271}{Numeric; embedding vector dimensions}
#' \item{V272}{Numeric; embedding vector dimensions}
#' \item{V273}{Numeric; embedding vector dimensions}
#' \item{V274}{Numeric; embedding vector dimensions}
#' \item{V275}{Numeric; embedding vector dimensions}
#' \item{V276}{Numeric; embedding vector dimensions}
#' \item{V277}{Numeric; embedding vector dimensions}
#' \item{V278}{Numeric; embedding vector dimensions}
#' \item{V279}{Numeric; embedding vector dimensions}
#' \item{V280}{Numeric; embedding vector dimensions}
#' \item{V281}{Numeric; embedding vector dimensions}
#' \item{V282}{Numeric; embedding vector dimensions}
#' \item{V283}{Numeric; embedding vector dimensions}
#' \item{V284}{Numeric; embedding vector dimensions}
#' \item{V285}{Numeric; embedding vector dimensions}
#' \item{V286}{Numeric; embedding vector dimensions}
#' \item{V287}{Numeric; embedding vector dimensions}
#' \item{V288}{Numeric; embedding vector dimensions}
#' \item{V289}{Numeric; embedding vector dimensions}
#' \item{V290}{Numeric; embedding vector dimensions}
#' \item{V291}{Numeric; embedding vector dimensions}
#' \item{V292}{Numeric; embedding vector dimensions}
#' \item{V293}{Numeric; embedding vector dimensions}
#' \item{V294}{Numeric; embedding vector dimensions}
#' \item{V295}{Numeric; embedding vector dimensions}
#' \item{V296}{Numeric; embedding vector dimensions}
#' \item{V297}{Numeric; embedding vector dimensions}
#' \item{V298}{Numeric; embedding vector dimensions}
#' \item{V299}{Numeric; embedding vector dimensions}
#' \item{V300}{Numeric; embedding vector dimensions}
#' \item{V301}{Numeric; embedding vector dimensions}
#' \item{V302}{Numeric; embedding vector dimensions}
#' \item{V303}{Numeric; embedding vector dimensions}
#' \item{V304}{Numeric; embedding vector dimensions}
#' \item{V305}{Numeric; embedding vector dimensions}
#' \item{V306}{Numeric; embedding vector dimensions}
#' \item{V307}{Numeric; embedding vector dimensions}
#' \item{V308}{Numeric; embedding vector dimensions}
#' \item{V309}{Numeric; embedding vector dimensions}
#' \item{V310}{Numeric; embedding vector dimensions}
#' \item{V311}{Numeric; embedding vector dimensions}
#' \item{V312}{Numeric; embedding vector dimensions}
#' \item{V313}{Numeric; embedding vector dimensions}
#' \item{V314}{Numeric; embedding vector dimensions}
#' \item{V315}{Numeric; embedding vector dimensions}
#' \item{V316}{Numeric; embedding vector dimensions}
#' \item{V317}{Numeric; embedding vector dimensions}
#' \item{V318}{Numeric; embedding vector dimensions}
#' \item{V319}{Numeric; embedding vector dimensions}
#' \item{V320}{Numeric; embedding vector dimensions}
#' \item{V321}{Numeric; embedding vector dimensions}
#' \item{V322}{Numeric; embedding vector dimensions}
#' \item{V323}{Numeric; embedding vector dimensions}
#' \item{V324}{Numeric; embedding vector dimensions}
#' \item{V325}{Numeric; embedding vector dimensions}
#' \item{V326}{Numeric; embedding vector dimensions}
#' \item{V327}{Numeric; embedding vector dimensions}
#' \item{V328}{Numeric; embedding vector dimensions}
#' \item{V329}{Numeric; embedding vector dimensions}
#' \item{V330}{Numeric; embedding vector dimensions}
#' \item{V331}{Numeric; embedding vector dimensions}
#' \item{V332}{Numeric; embedding vector dimensions}
#' \item{V333}{Numeric; embedding vector dimensions}
#' \item{V334}{Numeric; embedding vector dimensions}
#' \item{V335}{Numeric; embedding vector dimensions}
#' \item{V336}{Numeric; embedding vector dimensions}
#' \item{V337}{Numeric; embedding vector dimensions}
#' \item{V338}{Numeric; embedding vector dimensions}
#' \item{V339}{Numeric; embedding vector dimensions}
#' \item{V340}{Numeric; embedding vector dimensions}
#' \item{V341}{Numeric; embedding vector dimensions}
#' \item{V342}{Numeric; embedding vector dimensions}
#' \item{V343}{Numeric; embedding vector dimensions}
#' \item{V344}{Numeric; embedding vector dimensions}
#' \item{V345}{Numeric; embedding vector dimensions}
#' \item{V346}{Numeric; embedding vector dimensions}
#' \item{V347}{Numeric; embedding vector dimensions}
#' \item{V348}{Numeric; embedding vector dimensions}
#' \item{V349}{Numeric; embedding vector dimensions}
#' \item{V350}{Numeric; embedding vector dimensions}
#' \item{V351}{Numeric; embedding vector dimensions}
#' \item{V352}{Numeric; embedding vector dimensions}
#' \item{V353}{Numeric; embedding vector dimensions}
#' \item{V354}{Numeric; embedding vector dimensions}
#' \item{V355}{Numeric; embedding vector dimensions}
#' \item{V356}{Numeric; embedding vector dimensions}
#' \item{V357}{Numeric; embedding vector dimensions}
#' \item{V358}{Numeric; embedding vector dimensions}
#' \item{V359}{Numeric; embedding vector dimensions}
#' \item{V360}{Numeric; embedding vector dimensions}
#' \item{V361}{Numeric; embedding vector dimensions}
#' \item{V362}{Numeric; embedding vector dimensions}
#' \item{V363}{Numeric; embedding vector dimensions}
#' \item{V364}{Numeric; embedding vector dimensions}
#' \item{V365}{Numeric; embedding vector dimensions}
#' \item{V366}{Numeric; embedding vector dimensions}
#' \item{V367}{Numeric; embedding vector dimensions}
#' \item{V368}{Numeric; embedding vector dimensions}
#' \item{V369}{Numeric; embedding vector dimensions}
#' \item{V370}{Numeric; embedding vector dimensions}
#' \item{V371}{Numeric; embedding vector dimensions}
#' \item{V372}{Numeric; embedding vector dimensions}
#' \item{V373}{Numeric; embedding vector dimensions}
#' \item{V374}{Numeric; embedding vector dimensions}
#' \item{V375}{Numeric; embedding vector dimensions}
#' \item{V376}{Numeric; embedding vector dimensions}
#' \item{V377}{Numeric; embedding vector dimensions}
#' \item{V378}{Numeric; embedding vector dimensions}
#' \item{V379}{Numeric; embedding vector dimensions}
#' \item{V380}{Numeric; embedding vector dimensions}
#' \item{V381}{Numeric; embedding vector dimensions}
#' \item{V382}{Numeric; embedding vector dimensions}
#' \item{V383}{Numeric; embedding vector dimensions}
#' \item{V384}{Numeric; embedding vector dimensions}
#' \item{V385}{Numeric; embedding vector dimensions}
#' \item{V386}{Numeric; embedding vector dimensions}
#' \item{V387}{Numeric; embedding vector dimensions}
#' \item{V388}{Numeric; embedding vector dimensions}
#' \item{V389}{Numeric; embedding vector dimensions}
#' \item{V390}{Numeric; embedding vector dimensions}
#' \item{V391}{Numeric; embedding vector dimensions}
#' \item{V392}{Numeric; embedding vector dimensions}
#' \item{V393}{Numeric; embedding vector dimensions}
#' \item{V394}{Numeric; embedding vector dimensions}
#' \item{V395}{Numeric; embedding vector dimensions}
#' \item{V396}{Numeric; embedding vector dimensions}
#' \item{V397}{Numeric; embedding vector dimensions}
#' \item{V398}{Numeric; embedding vector dimensions}
#' \item{V399}{Numeric; embedding vector dimensions}
#' \item{V400}{Numeric; embedding vector dimensions}
#' \item{V401}{Numeric; embedding vector dimensions}
#' \item{V402}{Numeric; embedding vector dimensions}
#' \item{V403}{Numeric; embedding vector dimensions}
#' \item{V404}{Numeric; embedding vector dimensions}
#' \item{V405}{Numeric; embedding vector dimensions}
#' \item{V406}{Numeric; embedding vector dimensions}
#' \item{V407}{Numeric; embedding vector dimensions}
#' \item{V408}{Numeric; embedding vector dimensions}
#' \item{V409}{Numeric; embedding vector dimensions}
#' \item{V410}{Numeric; embedding vector dimensions}
#' \item{V411}{Numeric; embedding vector dimensions}
#' \item{V412}{Numeric; embedding vector dimensions}
#' \item{V413}{Numeric; embedding vector dimensions}
#' \item{V414}{Numeric; embedding vector dimensions}
#' \item{V415}{Numeric; embedding vector dimensions}
#' \item{V416}{Numeric; embedding vector dimensions}
#' \item{V417}{Numeric; embedding vector dimensions}
#' \item{V418}{Numeric; embedding vector dimensions}
#' \item{V419}{Numeric; embedding vector dimensions}
#' \item{V420}{Numeric; embedding vector dimensions}
#' \item{V421}{Numeric; embedding vector dimensions}
#' \item{V422}{Numeric; embedding vector dimensions}
#' \item{V423}{Numeric; embedding vector dimensions}
#' \item{V424}{Numeric; embedding vector dimensions}
#' \item{V425}{Numeric; embedding vector dimensions}
#' \item{V426}{Numeric; embedding vector dimensions}
#' \item{V427}{Numeric; embedding vector dimensions}
#' \item{V428}{Numeric; embedding vector dimensions}
#' \item{V429}{Numeric; embedding vector dimensions}
#' \item{V430}{Numeric; embedding vector dimensions}
#' \item{V431}{Numeric; embedding vector dimensions}
#' \item{V432}{Numeric; embedding vector dimensions}
#' \item{V433}{Numeric; embedding vector dimensions}
#' \item{V434}{Numeric; embedding vector dimensions}
#' \item{V435}{Numeric; embedding vector dimensions}
#' \item{V436}{Numeric; embedding vector dimensions}
#' \item{V437}{Numeric; embedding vector dimensions}
#' \item{V438}{Numeric; embedding vector dimensions}
#' \item{V439}{Numeric; embedding vector dimensions}
#' \item{V440}{Numeric; embedding vector dimensions}
#' \item{V441}{Numeric; embedding vector dimensions}
#' \item{V442}{Numeric; embedding vector dimensions}
#' \item{V443}{Numeric; embedding vector dimensions}
#' \item{V444}{Numeric; embedding vector dimensions}
#' \item{V445}{Numeric; embedding vector dimensions}
#' \item{V446}{Numeric; embedding vector dimensions}
#' \item{V447}{Numeric; embedding vector dimensions}
#' \item{V448}{Numeric; embedding vector dimensions}
#' \item{V449}{Numeric; embedding vector dimensions}
#' \item{V450}{Numeric; embedding vector dimensions}
#' \item{V451}{Numeric; embedding vector dimensions}
#' \item{V452}{Numeric; embedding vector dimensions}
#' \item{V453}{Numeric; embedding vector dimensions}
#' \item{V454}{Numeric; embedding vector dimensions}
#' \item{V455}{Numeric; embedding vector dimensions}
#' \item{V456}{Numeric; embedding vector dimensions}
#' \item{V457}{Numeric; embedding vector dimensions}
#' \item{V458}{Numeric; embedding vector dimensions}
#' \item{V459}{Numeric; embedding vector dimensions}
#' \item{V460}{Numeric; embedding vector dimensions}
#' \item{V461}{Numeric; embedding vector dimensions}
#' \item{V462}{Numeric; embedding vector dimensions}
#' \item{V463}{Numeric; embedding vector dimensions}
#' \item{V464}{Numeric; embedding vector dimensions}
#' \item{V465}{Numeric; embedding vector dimensions}
#' \item{V466}{Numeric; embedding vector dimensions}
#' \item{V467}{Numeric; embedding vector dimensions}
#' \item{V468}{Numeric; embedding vector dimensions}
#' \item{V469}{Numeric; embedding vector dimensions}
#' \item{V470}{Numeric; embedding vector dimensions}
#' \item{V471}{Numeric; embedding vector dimensions}
#' \item{V472}{Numeric; embedding vector dimensions}
#' \item{V473}{Numeric; embedding vector dimensions}
#' \item{V474}{Numeric; embedding vector dimensions}
#' \item{V475}{Numeric; embedding vector dimensions}
#' \item{V476}{Numeric; embedding vector dimensions}
#' \item{V477}{Numeric; embedding vector dimensions}
#' \item{V478}{Numeric; embedding vector dimensions}
#' \item{V479}{Numeric; embedding vector dimensions}
#' \item{V480}{Numeric; embedding vector dimensions}
#' \item{V481}{Numeric; embedding vector dimensions}
#' \item{V482}{Numeric; embedding vector dimensions}
#' \item{V483}{Numeric; embedding vector dimensions}
#' \item{V484}{Numeric; embedding vector dimensions}
#' \item{V485}{Numeric; embedding vector dimensions}
#' \item{V486}{Numeric; embedding vector dimensions}
#' \item{V487}{Numeric; embedding vector dimensions}
#' \item{V488}{Numeric; embedding vector dimensions}
#' \item{V489}{Numeric; embedding vector dimensions}
#' \item{V490}{Numeric; embedding vector dimensions}
#' \item{V491}{Numeric; embedding vector dimensions}
#' \item{V492}{Numeric; embedding vector dimensions}
#' \item{V493}{Numeric; embedding vector dimensions}
#' \item{V494}{Numeric; embedding vector dimensions}
#' \item{V495}{Numeric; embedding vector dimensions}
#' \item{V496}{Numeric; embedding vector dimensions}
#' \item{V497}{Numeric; embedding vector dimensions}
#' \item{V498}{Numeric; embedding vector dimensions}
#' \item{V499}{Numeric; embedding vector dimensions}
#' \item{V500}{Numeric; embedding vector dimensions}
#' \item{V501}{Numeric; embedding vector dimensions}
#' \item{V502}{Numeric; embedding vector dimensions}
#' \item{V503}{Numeric; embedding vector dimensions}
#' \item{V504}{Numeric; embedding vector dimensions}
#' \item{V505}{Numeric; embedding vector dimensions}
#' \item{V506}{Numeric; embedding vector dimensions}
#' \item{V507}{Numeric; embedding vector dimensions}
#' \item{V508}{Numeric; embedding vector dimensions}
#' \item{V509}{Numeric; embedding vector dimensions}
#' \item{V510}{Numeric; embedding vector dimensions}
#' \item{V511}{Numeric; embedding vector dimensions}
#' \item{V512}{Numeric; embedding vector dimensions}
#' \item{V513}{Numeric; embedding vector dimensions}
#' \item{V514}{Numeric; embedding vector dimensions}
#' \item{V515}{Numeric; embedding vector dimensions}
#' \item{V516}{Numeric; embedding vector dimensions}
#' \item{V517}{Numeric; embedding vector dimensions}
#' \item{V518}{Numeric; embedding vector dimensions}
#' \item{V519}{Numeric; embedding vector dimensions}
#' \item{V520}{Numeric; embedding vector dimensions}
#' \item{V521}{Numeric; embedding vector dimensions}
#' \item{V522}{Numeric; embedding vector dimensions}
#' \item{V523}{Numeric; embedding vector dimensions}
#' \item{V524}{Numeric; embedding vector dimensions}
#' \item{V525}{Numeric; embedding vector dimensions}
#' \item{V526}{Numeric; embedding vector dimensions}
#' \item{V527}{Numeric; embedding vector dimensions}
#' \item{V528}{Numeric; embedding vector dimensions}
#' \item{V529}{Numeric; embedding vector dimensions}
#' \item{V530}{Numeric; embedding vector dimensions}
#' \item{V531}{Numeric; embedding vector dimensions}
#' \item{V532}{Numeric; embedding vector dimensions}
#' \item{V533}{Numeric; embedding vector dimensions}
#' \item{V534}{Numeric; embedding vector dimensions}
#' \item{V535}{Numeric; embedding vector dimensions}
#' \item{V536}{Numeric; embedding vector dimensions}
#' \item{V537}{Numeric; embedding vector dimensions}
#' \item{V538}{Numeric; embedding vector dimensions}
#' \item{V539}{Numeric; embedding vector dimensions}
#' \item{V540}{Numeric; embedding vector dimensions}
#' \item{V541}{Numeric; embedding vector dimensions}
#' \item{V542}{Numeric; embedding vector dimensions}
#' \item{V543}{Numeric; embedding vector dimensions}
#' \item{V544}{Numeric; embedding vector dimensions}
#' \item{V545}{Numeric; embedding vector dimensions}
#' \item{V546}{Numeric; embedding vector dimensions}
#' \item{V547}{Numeric; embedding vector dimensions}
#' \item{V548}{Numeric; embedding vector dimensions}
#' \item{V549}{Numeric; embedding vector dimensions}
#' \item{V550}{Numeric; embedding vector dimensions}
#' \item{V551}{Numeric; embedding vector dimensions}
#' \item{V552}{Numeric; embedding vector dimensions}
#' \item{V553}{Numeric; embedding vector dimensions}
#' \item{V554}{Numeric; embedding vector dimensions}
#' \item{V555}{Numeric; embedding vector dimensions}
#' \item{V556}{Numeric; embedding vector dimensions}
#' \item{V557}{Numeric; embedding vector dimensions}
#' \item{V558}{Numeric; embedding vector dimensions}
#' \item{V559}{Numeric; embedding vector dimensions}
#' \item{V560}{Numeric; embedding vector dimensions}
#' \item{V561}{Numeric; embedding vector dimensions}
#' \item{V562}{Numeric; embedding vector dimensions}
#' \item{V563}{Numeric; embedding vector dimensions}
#' \item{V564}{Numeric; embedding vector dimensions}
#' \item{V565}{Numeric; embedding vector dimensions}
#' \item{V566}{Numeric; embedding vector dimensions}
#' \item{V567}{Numeric; embedding vector dimensions}
#' \item{V568}{Numeric; embedding vector dimensions}
#' \item{V569}{Numeric; embedding vector dimensions}
#' \item{V570}{Numeric; embedding vector dimensions}
#' \item{V571}{Numeric; embedding vector dimensions}
#' \item{V572}{Numeric; embedding vector dimensions}
#' \item{V573}{Numeric; embedding vector dimensions}
#' \item{V574}{Numeric; embedding vector dimensions}
#' \item{V575}{Numeric; embedding vector dimensions}
#' \item{V576}{Numeric; embedding vector dimensions}
#' \item{V577}{Numeric; embedding vector dimensions}
#' \item{V578}{Numeric; embedding vector dimensions}
#' \item{V579}{Numeric; embedding vector dimensions}
#' \item{V580}{Numeric; embedding vector dimensions}
#' \item{V581}{Numeric; embedding vector dimensions}
#' \item{V582}{Numeric; embedding vector dimensions}
#' \item{V583}{Numeric; embedding vector dimensions}
#' \item{V584}{Numeric; embedding vector dimensions}
#' \item{V585}{Numeric; embedding vector dimensions}
#' \item{V586}{Numeric; embedding vector dimensions}
#' \item{V587}{Numeric; embedding vector dimensions}
#' \item{V588}{Numeric; embedding vector dimensions}
#' \item{V589}{Numeric; embedding vector dimensions}
#' \item{V590}{Numeric; embedding vector dimensions}
#' \item{V591}{Numeric; embedding vector dimensions}
#' \item{V592}{Numeric; embedding vector dimensions}
#' \item{V593}{Numeric; embedding vector dimensions}
#' \item{V594}{Numeric; embedding vector dimensions}
#' \item{V595}{Numeric; embedding vector dimensions}
#' \item{V596}{Numeric; embedding vector dimensions}
#' \item{V597}{Numeric; embedding vector dimensions}
#' \item{V598}{Numeric; embedding vector dimensions}
#' \item{V599}{Numeric; embedding vector dimensions}
#' \item{V600}{Numeric; embedding vector dimensions}
#' \item{V601}{Numeric; embedding vector dimensions}
#' \item{V602}{Numeric; embedding vector dimensions}
#' \item{V603}{Numeric; embedding vector dimensions}
#' \item{V604}{Numeric; embedding vector dimensions}
#' \item{V605}{Numeric; embedding vector dimensions}
#' \item{V606}{Numeric; embedding vector dimensions}
#' \item{V607}{Numeric; embedding vector dimensions}
#' \item{V608}{Numeric; embedding vector dimensions}
#' \item{V609}{Numeric; embedding vector dimensions}
#' \item{V610}{Numeric; embedding vector dimensions}
#' \item{V611}{Numeric; embedding vector dimensions}
#' \item{V612}{Numeric; embedding vector dimensions}
#' \item{V613}{Numeric; embedding vector dimensions}
#' \item{V614}{Numeric; embedding vector dimensions}
#' \item{V615}{Numeric; embedding vector dimensions}
#' \item{V616}{Numeric; embedding vector dimensions}
#' \item{V617}{Numeric; embedding vector dimensions}
#' \item{V618}{Numeric; embedding vector dimensions}
#' \item{V619}{Numeric; embedding vector dimensions}
#' \item{V620}{Numeric; embedding vector dimensions}
#' \item{V621}{Numeric; embedding vector dimensions}
#' \item{V622}{Numeric; embedding vector dimensions}
#' \item{V623}{Numeric; embedding vector dimensions}
#' \item{V624}{Numeric; embedding vector dimensions}
#' \item{V625}{Numeric; embedding vector dimensions}
#' \item{V626}{Numeric; embedding vector dimensions}
#' \item{V627}{Numeric; embedding vector dimensions}
#' \item{V628}{Numeric; embedding vector dimensions}
#' \item{V629}{Numeric; embedding vector dimensions}
#' \item{V630}{Numeric; embedding vector dimensions}
#' \item{V631}{Numeric; embedding vector dimensions}
#' \item{V632}{Numeric; embedding vector dimensions}
#' \item{V633}{Numeric; embedding vector dimensions}
#' \item{V634}{Numeric; embedding vector dimensions}
#' \item{V635}{Numeric; embedding vector dimensions}
#' \item{V636}{Numeric; embedding vector dimensions}
#' \item{V637}{Numeric; embedding vector dimensions}
#' \item{V638}{Numeric; embedding vector dimensions}
#' \item{V639}{Numeric; embedding vector dimensions}
#' \item{V640}{Numeric; embedding vector dimensions}
#' \item{V641}{Numeric; embedding vector dimensions}
#' \item{V642}{Numeric; embedding vector dimensions}
#' \item{V643}{Numeric; embedding vector dimensions}
#' \item{V644}{Numeric; embedding vector dimensions}
#' \item{V645}{Numeric; embedding vector dimensions}
#' \item{V646}{Numeric; embedding vector dimensions}
#' \item{V647}{Numeric; embedding vector dimensions}
#' \item{V648}{Numeric; embedding vector dimensions}
#' \item{V649}{Numeric; embedding vector dimensions}
#' \item{V650}{Numeric; embedding vector dimensions}
#' \item{V651}{Numeric; embedding vector dimensions}
#' \item{V652}{Numeric; embedding vector dimensions}
#' \item{V653}{Numeric; embedding vector dimensions}
#' \item{V654}{Numeric; embedding vector dimensions}
#' \item{V655}{Numeric; embedding vector dimensions}
#' \item{V656}{Numeric; embedding vector dimensions}
#' \item{V657}{Numeric; embedding vector dimensions}
#' \item{V658}{Numeric; embedding vector dimensions}
#' \item{V659}{Numeric; embedding vector dimensions}
#' \item{V660}{Numeric; embedding vector dimensions}
#' \item{V661}{Numeric; embedding vector dimensions}
#' \item{V662}{Numeric; embedding vector dimensions}
#' \item{V663}{Numeric; embedding vector dimensions}
#' \item{V664}{Numeric; embedding vector dimensions}
#' \item{V665}{Numeric; embedding vector dimensions}
#' \item{V666}{Numeric; embedding vector dimensions}
#' \item{V667}{Numeric; embedding vector dimensions}
#' \item{V668}{Numeric; embedding vector dimensions}
#' \item{V669}{Numeric; embedding vector dimensions}
#' \item{V670}{Numeric; embedding vector dimensions}
#' \item{V671}{Numeric; embedding vector dimensions}
#' \item{V672}{Numeric; embedding vector dimensions}
#' \item{V673}{Numeric; embedding vector dimensions}
#' \item{V674}{Numeric; embedding vector dimensions}
#' \item{V675}{Numeric; embedding vector dimensions}
#' \item{V676}{Numeric; embedding vector dimensions}
#' \item{V677}{Numeric; embedding vector dimensions}
#' \item{V678}{Numeric; embedding vector dimensions}
#' \item{V679}{Numeric; embedding vector dimensions}
#' \item{V680}{Numeric; embedding vector dimensions}
#' \item{V681}{Numeric; embedding vector dimensions}
#' \item{V682}{Numeric; embedding vector dimensions}
#' \item{V683}{Numeric; embedding vector dimensions}
#' \item{V684}{Numeric; embedding vector dimensions}
#' \item{V685}{Numeric; embedding vector dimensions}
#' \item{V686}{Numeric; embedding vector dimensions}
#' \item{V687}{Numeric; embedding vector dimensions}
#' \item{V688}{Numeric; embedding vector dimensions}
#' \item{V689}{Numeric; embedding vector dimensions}
#' \item{V690}{Numeric; embedding vector dimensions}
#' \item{V691}{Numeric; embedding vector dimensions}
#' \item{V692}{Numeric; embedding vector dimensions}
#' \item{V693}{Numeric; embedding vector dimensions}
#' \item{V694}{Numeric; embedding vector dimensions}
#' \item{V695}{Numeric; embedding vector dimensions}
#' \item{V696}{Numeric; embedding vector dimensions}
#' \item{V697}{Numeric; embedding vector dimensions}
#' \item{V698}{Numeric; embedding vector dimensions}
#' \item{V699}{Numeric; embedding vector dimensions}
#' \item{V700}{Numeric; embedding vector dimensions}
#' \item{V701}{Numeric; embedding vector dimensions}
#' \item{V702}{Numeric; embedding vector dimensions}
#' \item{V703}{Numeric; embedding vector dimensions}
#' \item{V704}{Numeric; embedding vector dimensions}
#' \item{V705}{Numeric; embedding vector dimensions}
#' \item{V706}{Numeric; embedding vector dimensions}
#' \item{V707}{Numeric; embedding vector dimensions}
#' \item{V708}{Numeric; embedding vector dimensions}
#' \item{V709}{Numeric; embedding vector dimensions}
#' \item{V710}{Numeric; embedding vector dimensions}
#' \item{V711}{Numeric; embedding vector dimensions}
#' \item{V712}{Numeric; embedding vector dimensions}
#' \item{V713}{Numeric; embedding vector dimensions}
#' \item{V714}{Numeric; embedding vector dimensions}
#' \item{V715}{Numeric; embedding vector dimensions}
#' \item{V716}{Numeric; embedding vector dimensions}
#' \item{V717}{Numeric; embedding vector dimensions}
#' \item{V718}{Numeric; embedding vector dimensions}
#' \item{V719}{Numeric; embedding vector dimensions}
#' \item{V720}{Numeric; embedding vector dimensions}
#' \item{V721}{Numeric; embedding vector dimensions}
#' \item{V722}{Numeric; embedding vector dimensions}
#' \item{V723}{Numeric; embedding vector dimensions}
#' \item{V724}{Numeric; embedding vector dimensions}
#' \item{V725}{Numeric; embedding vector dimensions}
#' \item{V726}{Numeric; embedding vector dimensions}
#' \item{V727}{Numeric; embedding vector dimensions}
#' \item{V728}{Numeric; embedding vector dimensions}
#' \item{V729}{Numeric; embedding vector dimensions}
#' \item{V730}{Numeric; embedding vector dimensions}
#' \item{V731}{Numeric; embedding vector dimensions}
#' \item{V732}{Numeric; embedding vector dimensions}
#' \item{V733}{Numeric; embedding vector dimensions}
#' \item{V734}{Numeric; embedding vector dimensions}
#' \item{V735}{Numeric; embedding vector dimensions}
#' \item{V736}{Numeric; embedding vector dimensions}
#' \item{V737}{Numeric; embedding vector dimensions}
#' \item{V738}{Numeric; embedding vector dimensions}
#' \item{V739}{Numeric; embedding vector dimensions}
#' \item{V740}{Numeric; embedding vector dimensions}
#' \item{V741}{Numeric; embedding vector dimensions}
#' \item{V742}{Numeric; embedding vector dimensions}
#' \item{V743}{Numeric; embedding vector dimensions}
#' \item{V744}{Numeric; embedding vector dimensions}
#' \item{V745}{Numeric; embedding vector dimensions}
#' \item{V746}{Numeric; embedding vector dimensions}
#' \item{V747}{Numeric; embedding vector dimensions}
#' \item{V748}{Numeric; embedding vector dimensions}
#' \item{V749}{Numeric; embedding vector dimensions}
#' \item{V750}{Numeric; embedding vector dimensions}
#' \item{V751}{Numeric; embedding vector dimensions}
#' \item{V752}{Numeric; embedding vector dimensions}
#' \item{V753}{Numeric; embedding vector dimensions}
#' \item{V754}{Numeric; embedding vector dimensions}
#' \item{V755}{Numeric; embedding vector dimensions}
#' \item{V756}{Numeric; embedding vector dimensions}
#' \item{V757}{Numeric; embedding vector dimensions}
#' \item{V758}{Numeric; embedding vector dimensions}
#' \item{V759}{Numeric; embedding vector dimensions}
#' \item{V760}{Numeric; embedding vector dimensions}
#' \item{V761}{Numeric; embedding vector dimensions}
#' \item{V762}{Numeric; embedding vector dimensions}
#' \item{V763}{Numeric; embedding vector dimensions}
#' \item{V764}{Numeric; embedding vector dimensions}
#' \item{V765}{Numeric; embedding vector dimensions}
#' \item{V766}{Numeric; embedding vector dimensions}
#' \item{V767}{Numeric; embedding vector dimensions}
#' \item{V768}{Numeric; embedding vector dimensions}
#' }
#' @source Generated using Hugging Face embedding model via EndpointR functions
"single_embedding_hf"
